[__config__]
oldver = "old.json"
newver = "new.json"

[atuin]
source = "github"
github = "atuinsh/atuin"
use_latest_release = true
prefix = "v"

[grafana]
source = "github"
github = "grafana/grafana"
use_latest_release = true
prefix = "v"
